server:
  port: 8000

spring:
  application:
    name: gateway-service

    cloud:
      gateway:
        routes:
          - id: user-service
            uri: http://localhost:50010
            predicates:
              - Path=/user/**
#  cloud:
#    config:
#      uri: http://172.17.0.1:8888
#      name: gateway-server
#      profile: test

eureka:
  instance:
    instance-id: gateway-msa-instance

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
